import React, { useEffect, useMemo, useState } from 'react'
import { DragDropContext, Droppable, Draggable } from '@hello-pangea/dnd'
import { api } from './api/client'
const columns = ['Backlog','To Do','In Progress','In Review','Done']
const views = ['projects','kanban','approval','calendar','agents','usage']
export default function App(){
  const [view,setView]=useState('projects'); const [projects,setProjects]=useState([]); const [agents,setAgents]=useState([]); const [tasks,setTasks]=useState([]); const [sprints,setSprints]=useState([]); const [usage,setUsage]=useState({rows:[],totals:[]}); const [projectId,setProjectId]=useState(null)
  const load=async()=>{const [p,a,t,s,u]=await Promise.all([api('/api/projects'),api('/api/agents'),api('/api/tasks'),api('/api/sprints'),api('/api/usage/tokens')]); setProjects(p); setAgents(a); setTasks(t); setSprints(s); setUsage(u); if(!projectId&&p[0]) setProjectId(p[0].id)}
  useEffect(()=>{load()},[])
  const projectTasks=tasks.filter(t=>!projectId||t.project_id===projectId)
  const change=async(id,patch)=>{await api(`/api/tasks/${id}`,{method:'PATCH',body:JSON.stringify(patch)}); load()}
  const onDragEnd=async r=>{if(!r.destination) return; await change(Number(r.draggableId),{status:r.destination.droppableId})}
  const createTask=async()=>{const title=prompt('Task title?'); if(!title) return; await api('/api/tasks',{method:'POST',body:JSON.stringify({project_id:projectId,title,assignee_id:'utkarsh',reporter_id:'utkarsh',status:'Backlog'})}); load()}
  const createProject=async()=>{const name=prompt('Project name?'); if(!name) return; await api('/api/projects',{method:'POST',body:JSON.stringify({name,lead_agent_id:'gandalf'})}); load()}
  const board=useMemo(()=>columns.map(c=>({name:c,items:projectTasks.filter(t=>t.status===c)})),[projectTasks])
  return <div className="app"><aside className="side"><div className="top"><b>🦞 AgentOS</b></div><div className="nav">{views.map(v=><button key={v} onClick={()=>setView(v)}>{v}</button>)}</div><div style={{marginTop:14}} className="card"><div className="small">Projects</div>{projects.map(p=><div key={p.id} className={`stat ${projectId===p.id?'active':''}`} onClick={()=>setProjectId(p.id)}>{p.name}<div className="muted">{p.task_count} tasks, {p['% done']}% done</div></div>)}</div></aside><main className="main"><div className="top"><div><h2 style={{margin:0}}>{view}</h2><div className="muted">localhost:3000 UI, API on localhost:8000</div></div><div className="row"><button onClick={createProject}>New project</button><button onClick={createTask}>New task</button></div></div>{view==='projects'&&<div className="grid">{projects.map(p=><div className="card" key={p.id}><b>{p.name}</b><div className="muted">Lead {p.lead_agent_name}, {p.status}, {p.task_count} tasks</div></div>)}</div>}{view==='kanban'&&<DragDropContext onDragEnd={onDragEnd}><div className="cols">{board.map(col=><div className="card" key={col.name}><b>{col.name}</b><Droppable droppableId={col.name}>{p=><div ref={p.innerRef} {...p.droppableProps} className="drop">{col.items.map((t,i)=><Draggable key={t.id} draggableId={String(t.id)} index={i}>{d=><div ref={d.innerRef} {...d.draggableProps} {...d.dragHandleProps} className="task"><b>{t.title}</b><div className="muted">{t.assignee_id} · {t.priority}</div></div>}</Draggable>)}{p.placeholder}</div>}</Droppable></div>)}</div></DragDropContext>}{view==='approval'&&<div className="grid">{tasks.filter(t=>t.assignee_id==='utkarsh').map(t=><div key={t.id} className="card"><b>{t.title}</b><div className="muted">Awaiting approval</div><div className="row"><button onClick={()=>change(t.id,{assignee_id:'gandalf',status:'To Do'})}>Approve</button><button onClick={()=>change(t.id,{status:'Rejected'})}>Reject</button></div></div>)}</div>}{view==='calendar'&&<div className="card"><div className="calendar">{Array.from({length:35}).map((_,i)=><div key={i} className="day">{projectTasks.filter(t=>t.due_date).slice(i,i+1).map(t=><div key={t.id} className="small">{t.title}</div>)}</div>)}</div></div>}{view==='agents'&&<div className="grid">{agents.map(a=><div key={a.id} className="card"><div className="row"><div style={{fontSize:28}}>{a.avatar}</div><div><b>{a.name}</b><div className="muted">{a.role}</div></div></div><div className="small">{a.model} · {a.provider}</div><div className="muted">{a.status} · {a.current_tasks} active</div></div>)}</div>}{view==='usage'&&<div className="grid"><div className="card"><table className="table"><thead><tr><th>Agent</th><th>Model</th><th>Tokens</th><th>Est. cost</th></tr></thead><tbody>{usage.rows.map((r,i)=><tr key={i}><td>{r.agent}</td><td>{r.model}</td><td>{r.tokens}</td><td>${r.estimated_cost}</td></tr>)}</tbody></table></div></div>}</main></div>
}
